import type { Metadata } from 'next'
import './globals.css'
import Header from '@/components/ui/sections/header'
import Footer from '@/components/ui/sections/footer'

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="pt-br">
      <body className={`antialiased flex flex-col justify-between items-start`}>
        <Header />
        {children}
        <Footer />
      </body>
    </html>
  )
}
